// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwJi_gzb0ikczPUfil3dFP6JwSuZKFGRM',
    appId: '1:416315563101:web:54c5490f524f427186c1b4',
    messagingSenderId: '416315563101',
    projectId: 'mobapp-d7eb8',
    authDomain: 'mobapp-d7eb8.firebaseapp.com',
    databaseURL: 'https://mobapp-d7eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobapp-d7eb8.appspot.com',
    measurementId: 'G-EZYGYGL7DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRVBCKQ6UFoWoaPbaQPq2AAlJVWMGP42g',
    appId: '1:416315563101:android:bab5223569836c6c86c1b4',
    messagingSenderId: '416315563101',
    projectId: 'mobapp-d7eb8',
    databaseURL: 'https://mobapp-d7eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobapp-d7eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOV6VS08BlPHKZ1FEddEtnEyDbJfZYrOY',
    appId: '1:416315563101:ios:871ced2f1c15257086c1b4',
    messagingSenderId: '416315563101',
    projectId: 'mobapp-d7eb8',
    databaseURL: 'https://mobapp-d7eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobapp-d7eb8.appspot.com',
    androidClientId: '416315563101-agk0bsknnajt38rd28l93titd77ove62.apps.googleusercontent.com',
    iosClientId: '416315563101-fiposbs8q3kk5fapp5b8dbifi1nlsq4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRealEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOV6VS08BlPHKZ1FEddEtnEyDbJfZYrOY',
    appId: '1:416315563101:ios:871ced2f1c15257086c1b4',
    messagingSenderId: '416315563101',
    projectId: 'mobapp-d7eb8',
    databaseURL: 'https://mobapp-d7eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobapp-d7eb8.appspot.com',
    androidClientId: '416315563101-agk0bsknnajt38rd28l93titd77ove62.apps.googleusercontent.com',
    iosClientId: '416315563101-fiposbs8q3kk5fapp5b8dbifi1nlsq4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRealEstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwJi_gzb0ikczPUfil3dFP6JwSuZKFGRM',
    appId: '1:416315563101:web:b1d7f2ec38d45fac86c1b4',
    messagingSenderId: '416315563101',
    projectId: 'mobapp-d7eb8',
    authDomain: 'mobapp-d7eb8.firebaseapp.com',
    databaseURL: 'https://mobapp-d7eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobapp-d7eb8.appspot.com',
    measurementId: 'G-ZL5569438C',
  );

}